; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "XFBrowser"
#define MyAppVersion "Release 1.3.0 "
#define MyAppPublisher "ZhouyiStudio"
#define MyAppURL "https://github.com/ZhouyiStudio/XFBrowser-Desktop"
#define MyAppExeName "XFBrowser.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3F2A34B2-35D5-4381-9843-2871C7C627CF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\LICENSE.electron.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\
OutputBaseFilename=XFBrowser-Desktop-1.3.0
SetupIconFile=C:\Users\Zhouyi\Downloads\e3ujj-iv6a0-001.ico
SolidCompression=yes
WizardStyle=modern polar

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\chrome_100_percent.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\chrome_200_percent.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\d3dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\dxcompiler.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\dxil.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\ffmpeg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\icudtl.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\LICENSE.electron.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\LICENSES.chromium.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\resources.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\snapshot_blob.bin"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\v8_context_snapshot.bin"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\vk_swiftshader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\vk_swiftshader_icd.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\vulkan-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\XFBrowser.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\locales\*"; DestDir: "{app}\locales"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Zhouyi\Desktop\gh-action-build-artifact\xfbrowser-win-unpacked\resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

