name: Build XFBrowser
on: push

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
